[package]
name = "async-task"
version = "1.1.1"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
edition = "2018"
license = "Apache-2.0/MIT"
repository = "https://github.com/async-rs/async-task"
homepage = "https://github.com/async-rs/async-task"
documentation = "https://docs.rs/async-task"
description = "Task abstraction for building executors"
keywords = ["futures", "task", "executor", "spawn"]
categories = ["asynchronous", "concurrency"]
readme = "README.md"

[dev-dependencies]
crossbeam = "0.7.3"
futures = "0.3.1"
lazy_static = "1.4.0"
crossbeam-utils = "0.7.0"
